### ISSUE TITLE
Best way to turn off for some deployment targets?

### ISSUE THREAD

**Issue by tonyd256** [ember-cli-deploy/ember-cli-deploy-manifest#12]
I have some deployment targets like dev and staging that don't compress the assets with a new hash in the name. So when using this plugin, my assets are not deployed because their file names aren't changing. What's the best way to turn this off for targets like these?

**Comment by kpfefferle** [comment]
@tonyd256 I think you could do the same "whitelisting by exclusion" strategy that I recommend for ember-cli-deploy-cloudfront here: https://github.com/kpfefferle/ember-cli-deploy-cloudfront#disable-in-selected-environments

ember-cli-deploy has [this WIP PR](https://github.com/ember-cli-deploy/ember-cli-deploy/pull/349) to allow for a more graceful plugin disable per environment in the future.

**Comment by achambers** [comment]
FYI - The PR @kpfefferle should be landing in the next day or so.

**Comment by tonyd256** [comment]
@kpfefferle That worked great! Thanks for the tip, I had no idea one could do that!
