### ISSUE TITLE
How to define files that should always be uploaded?

### ISSUE THREAD

**Issue by urbany** [ember-cli-deploy/ember-cli-deploy-manifest#15]
I have a `/service-worker.js` file I can't fingerprint and should always be uploaded.
I tried to do this but didn't work:

`ENV.manifest.filePattern = '**/!(service-worker.js).{json,js,css,png,gif,ico,jpg,xml,txt,svg,swf,eot,ttf,woff,woff2,htm}';`

It won't be added to the deploy manifest and won't be uploaded.

Anyway I can make this work?

**Comment by lukemelia** [comment]
Hi @urbany, I'm open to ways to make this more elegant, but my initial thought (assuming here you are using S3) is this:

Add a second instance (an "alias") of the S3 plugin which has `manifestPath` configured to `null` and `filePattern` configured to match only your `service-worker.js` file. For information about how to configure an alias, see the [Advanced Plugin Configuration section](http://ember-cli-deploy.com/docs/v1.0.x/configuration/#advanced-plugin-configuration) of the ember-cli-deploy docs.

Note that if you have HTTP caching layer(s) in your stack, for example with Cloudfront in front of your S3 bucket, you will need to configure those to have caching on that file, or perhaps a very short TTL.

Let us know how it works out.

**Comment by ntodd** [comment]
Just following up that the advice from @lukemelia does work (in my case for a `/manifest.appcache` file).  Thanks!

**Comment by urbany** [comment]
@ntodd Yes it works, sorry for the delay I forgot to comment. Thanks @lukemelia
