### ISSUE TITLE
Feature Request -- ability to omit files from manifest based on ignore pattern 

### ISSUE THREAD

**Issue by stephencattaneo** [ember-cli-deploy/ember-cli-deploy-manifest#18]
My use case is I need to deploy certain files to s3 on every deploy.  The files in question are not fingerprinted, but should always be deployed.   I can achieve this by not having the file present in the manifest.  Adding `ignoreFilePattern` would allow me to configure my deploy.js to ignore my always needed to deploy files.

Previously opened an issue to solve a different way in ember-cli-deploy-s3 --
 https://github.com/ember-cli-deploy/ember-cli-deploy-s3/issues/92

@achambers suggested this fix instead.

**Comment by achambers** [comment]
Closed by #19
