### ISSUE TITLE
Missing Configuration Doc

### ISSUE THREAD

**Issue by ccarterc** [ember-cli-deploy/ember-cli-deploy-manifest#22]
It's not clear where configs go in relation to `ENV`.  Can anyone provide 1 example?

**Comment by achambers** [comment]
@ccarterc Everything you need to know about this should be in the docs here http://ember-cli-deploy.com/docs/v1.0.x/configuration/

I’m going to close this but by all means, feel free to ask questions here or, even better, in the #ec-deploy channel on the Ember Community Slack team.
