### ISSUE TITLE
filePattern

### ISSUE THREAD

**Issue by buschtoens** [ember-cli-deploy/ember-cli-deploy-manifest#9]
The default `filePattern` for files to be included in the manifest is:

```js
"**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}"
```

If I understood correctly, plugins that respect the manifest (such as ember-cli-deploy-s3) will *only* ever upload files that they find listed in the manifest (if they have different fingerprints that is).

Doesn't that imply that all files not matching the pattern will be completely ignored?

Take `what-is-love.webm` for example. If (for whatever reason) someone needed to statically embed this webm video in their website, the video would never be uploaded, because it doesn't match the default file pattern. I did not actually test this though, but if I understood the docs correctly, precisely this would happen.

I can understand why a file filtering feature could be useful and don't advocate to remove it as a whole, but I'd set the default pattern to `"**/*"` so all files are matched. 
Or even better yet, set `filePattern: false` and implement a simple switch that skips the filtering for performance reasons if the `filePattern` is false-y. 
Alternatively we could test for `"**/*"` and just skip in that case to keep the human interface more intuitive.

If I did not miss any deeper reason for this and the change would be welcome, I'd make a quick PR. :grinning: 

Merry X-MAS everybody! :christmas_tree:

**Comment by buschtoens** [comment]
If the glob pattern is supposed to match the whole file name, this actually results in problems when used with ember-cli-deploy-gzip and `{ keep: true }`, as all gzipped files are saved as `my-app-1a2b3c.js.gz` and `.gz` isn't in the default pattern.

**Comment by lukemelia** [comment]
@buschtoens The manifest filePattern exists because you typically only want to match the files that should be uploaded to your assets server. i.e. you want to exclude index.html. You're correct that if you add other types of files, this plugin's filePattern config needs to be updated. I'm in theory open to improving the ergonomics of the default value, but I don't think of the solutions you proposed satisfy the basic requirement.

**Comment by buschtoens** [comment]
Oh yeah, that sounds logical. I'll think about that and see how the default configuration integrates in our workflow. I'll close for now and reopen if I come up with something better. :)
